package problems;

import java.util.Scanner;
/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.*/
public class FindDifference {

  public static void main(String[] args) {
    Scanner input = new Scanner(System.in);
    System.out.println("Enter first string 's'");
    String s = input.nextLine();
    System.out.println("Enter second string 't' ");
    String t = input.nextLine();
    input.close();
    FindDifference obj = new FindDifference();
    char ch = obj.findDifference(s,t);
    System.out.println(ch);
  }

  //TimeComplexity :O(n)
  public char findDifference(String s, String t) {
    int sumS = 0, sumT = 0;

    for (char ch : s.toCharArray()) {
      sumS += ch;

    }
    for (char ch : t.toCharArray()) {
      sumT += ch;
    }

    return (char) (sumT - sumS);
  }

}
